karion.net.pl:
  hostname: karion.net.pl
  user: karion
  port: 59184
#  configFile: ~/.ssh/config
#  identityFile: ~/.ssh/id_rsa
  stage: prod
  roles:
    - blog
  deploy_path: ~/domains/karion.net.pl/sculpin
  bin/php: /usr/local/php7.1/bin/php